### ISSUE TITLE
Trouble connecting to Ottobit (Enzo works great)

### ISSUE THREAD

**Issue by sciascia** [ElliotGarbus/Ottobit-Jr-Editor-and-Librarian#1]
Hi There, 

Firstly, thank you so much for creating these Meris librarians - amazing!

Secondly, while my Enzo works no problem, the Ottobit won't connect. I've triple-checked and set the Ottobit's global settings several times and tried different MIDI channels but have noticed a missing message compared with the Enzo's connection output.

When the Enzo connects, this 39 byte message for each preset appears...
![enzo](https://user-images.githubusercontent.com/875921/79266064-1e5c4800-7eeb-11ea-8b49-99a676ed1b3c.png)

But when connecting to the Ottobit, that message is missing which I assume is the preset data from the Ottobit...
![ottobit](https://user-images.githubusercontent.com/875921/79266100-2c11cd80-7eeb-11ea-97e4-aa2f93a38598.png)

Also, the Ottobit librarian never remembers the MIDI interface info in the connect window, is this because the librarian isn't successfully connecting or does it indicate something else?

Sorry for posting this as an issue, just not sure what I'm doing wrong. Any pointers in the right direction would be much appreciated.

Cheers

Ben

SETUP:
Mac –> UM-ONE –> Meris I/O –> Ottobit Jr Channel 3
Mac –> UM-ONE –> Meris I/O –> Enzo Channel 1
There's no other gear connected to the UM-ONE and have tried with the Enzo disconnected

**Comment by ElliotGarbus** [comment]
Make sure you have the midi thru set to OUT on the Ottobit Jr.
When you twist the knobs on the Ottobit Jr, do you see lights flashing on the UM-One?

**Comment by sciascia** [comment]
Thanks for the reply. Yes, MIDI Thru is set to out (have just re-set that) and when I turn the Ottobit's knobs, lights on the UM-ONE light up.

**Comment by sciascia** [comment]
Have just tried quitting the librarian and re-connecting and now it works. Will monitor this and see how I go.

Thanks heaps for the help. 

Cheers

Ben

**Comment by ElliotGarbus** [comment]
Thanks for letting me know.  Enjoy and stay healthy.
