### ISSUE TITLE
Unable to load program after first installation 

### ISSUE THREAD

**Issue by lfennew** [ElliotGarbus/Ottobit-Jr-Editor-and-Librarian#2]
i, I have installed the otto bit, hedra,and poly moon applications, I am unable to re-open these applications, they simply load and close instantly, during my initial start up I was able to open the application and view its features however I was unable to get the green connected icon on the application to my pedal, so I thought a quick open and close would solve the problem, now the applications won't open, both ottobit & hedra are unable to open/load, I installed the polymoon app out of curiosity and that has installed and opened without issue, but now I fear if I close that application will no longer be able to open it, I opened a file within the folder and got this message, ?

Last login: Mon Mar  1 23:14:42 on ttys000
/Applications/OttobitJrEdit.app/Contents/MacOS/OttobitJrEdit ; exit;
**_(Iveeditedmydetailshere)_**@MacBook-Pro ~ % /Applications/OttobitJrEdit.app/Contents/MacOS/OttobitJrEdit ; exit;
[INFO   ] [Logger      ] Record log in /Users/**_Editedmydetailshere._**kivy/logs/kivy_21-03-01_101.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/Applications/OttobitJrEdit.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] [Python      ] v3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] [Python      ] Interpreter at "/Applications/OttobitJrEdit.app/Contents/MacOS/OttobitJrEdit"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Failed creating OpenGL pixel format'
  File "site-packages/kivy/core/__init__.py", line 71, in core_select_lib
  File "site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
  File "site-packages/kivy/core/window/__init__.py", line 983, in __init__
  File "site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 232, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] [App         ] Unable to get a Window, abort.

Ive reinstalled the program numerous times and I am unable to even load the program, any help is greatly appreciated. fyi im urning Mac Catolina 10.15.7 

p.s im sure its fine but I have edited out my laptop name,
Thank you,

**Comment by ElliotGarbus** [comment]
FIrst make sure you have changed the security setting in Catalina to allow these applications to run.
Assuming you have done that, Each app creates a hidden directory.  To see hidden directories on the Mac type "command-shift-."
There is a directory .kivy/logs share the most recent log file for one of the applications.
This will help identify the issue.  Post the log file.
You will also see hidden directories .ottobit, .hedra, and .polymoon.  You can deleted the "main.ini" files from each of these directories.  If these files get corrupted it can cause an issue.

Let's start with one app - and get it fixed.  Then presumably we can get them all running. 

What hardware are you using to connect the Mac to the the pedals?

**Comment by lfennew** [comment]
thanks so much for this, so im in the directory and I can only  find two directories relating to Kivy or Kivy_install 

Kivy > 1. Core 2. graphics 3. lib [folders] and some some files called weak proxy.cpthyon-37m-darwin.so, I am unable to find the log files to share, are these a text file or under a specific file time? 

Kivy_instal > 1. Data 2. Modules within modules is a .py file that detailed the following


import threading
import json
from gc import get_objects, garbage
from kivy.clock import Clock
from kivy.cache import Cache
from collections import OrderedDict
from kivy.logger import Logger

try:
    from flask import Flask, render_template_string, make_response
except ImportError:
    Logger.error('WebDebugger: unable to import Flask. Install it!')
    raise

history_max = 250


class MissingOrderedDict(OrderedDict):

    def __missing__(self, key):
        self[key] = [0] * history_max
        return self[key]


metrics = MissingOrderedDict()
app = Flask(__name__)

The hardware I was using to connect the app was the midi/in out from my Arturia key lab 49 into a Meris IO, I hope this helps.

**Comment by ElliotGarbus** [comment]
That is not the correct directory.  Go to the home directory, then .kivy.

**Comment by lfennew** [comment]
apologies, found it!

[INFO   ] Logger: Record log in /Users/lewisennew/.kivy/logs/kivy_21-03-01_0.txt
[WARNING] [Config      ] Upgrading configuration in progress.
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/69BBCA67-A8E5-494E-896D-3F837B1A637F/d/OttobitJrEdit.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] Python: v3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] Python: Interpreter at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/69BBCA67-A8E5-494E-896D-3F837B1A637F/d/OttobitJrEdit.app/Contents/MacOS/OttobitJrEdit"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'2.1 NVIDIA-14.0.32 355.11.11.10.10.143'>
[INFO   ] GL: OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] GL: OpenGL renderer <b'NVIDIA GeForce GT 650M OpenGL Engine'>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <b'1.20'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
[INFO   ] Base: Start application main loop
[INFO   ] WindowSDL: exiting mainloop and closing.
[INFO   ] Base: Leaving application in progress...

**Comment by lfennew** [comment]
that was the first, this is the most recent
[INFO   ] Logger: Record log in /Users/lewisennew/.kivy/logs/kivy_21-03-01_115.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/Applications/OttobitJrEdit 2.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] Python: v3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] Python: Interpreter at "/Applications/OttobitJrEdit 2.app/Contents/MacOS/OttobitJrEdit"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Failed creating OpenGL pixel format'
  File "site-packages/kivy/core/__init__.py", line 71, in core_select_lib
  File "site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
  File "site-packages/kivy/core/window/__init__.py", line 983, in __init__
  File "site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 232, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] App: Unable to get a Window, abort.

**Comment by ElliotGarbus** [comment]
The first one shows no errors.  The second you posted is from running a random file in the build.  Look through the log files and see if can find one that indicates [ERROR] or {CRITICAL] near the bottom of the file.

**Comment by ElliotGarbus** [comment]
Or try running one of the apps again and then check for a log file.  SInce we are in the Ottobit page lets focus on Ottobit to start.

**Comment by lfennew** [comment]
[INFO   ] Logger: Record log in /Users/lewisennew/.kivy/logs/kivy_21-03-01_29.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/1F356529-8CB1-422B-8B2A-30F190945A0C/d/HedraEdit-5.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] Python: v3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]
[INFO   ] Python: Interpreter at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/1F356529-8CB1-422B-8B2A-30F190945A0C/d/HedraEdit-5.app/Contents/MacOS/HedraEdit"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Failed creating OpenGL pixel format'
  File "site-packages/kivy/core/__init__.py", line 71, in core_select_lib
  File "site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
  File "site-packages/kivy/core/window/__init__.py", line 983, in __init__
  File "site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 232, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] App: Unable to get a Window, abort.


-----------------------------

[INFO   ] Logger: Record log in /Users/lewisennew/.kivy/logs/kivy_21-03-01_109.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/74FCC366-43B6-40C9-933C-61D29CCADB2B/d/OttobitJrEdit.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] Python: v3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] Python: Interpreter at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/74FCC366-43B6-40C9-933C-61D29CCADB2B/d/OttobitJrEdit.app/Contents/MacOS/OttobitJrEdit"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Failed creating OpenGL pixel format'
  File "site-packages/kivy/core/__init__.py", line 71, in core_select_lib
  File "site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
  File "site-packages/kivy/core/window/__init__.py", line 983, in __init__
  File "site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 232, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] App: Unable to get a Window, abort.

=========================

this was the most recent attempt at opening otto bit ,


[INFO   ] Logger: Record log in /Users/lewisennew/.kivy/logs/kivy_21-03-02_0.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/Applications/OttobitJrEdit 2.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] Python: v3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] Python: Interpreter at "/Applications/OttobitJrEdit 2.app/Contents/MacOS/OttobitJrEdit"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Failed creating OpenGL pixel format'
  File "site-packages/kivy/core/__init__.py", line 71, in core_select_lib
  File "site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
  File "site-packages/kivy/core/window/__init__.py", line 983, in __init__
  File "site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 232, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] App: Unable to get a Window, abort.

**Comment by ElliotGarbus** [comment]
During the install you did you change the security settings in Catalina to enable the app to run?

**Comment by ElliotGarbus** [comment]
On the Mac, in settings go to security and privacy, on the general tab there are options to allow downloaded apps, and specifically to enable the app you just installed.

**Comment by lfennew** [comment]
Hi Elliot, I this could have happened, it popped up saying to open the application regardless of it being unsafe and I selected Allow. However since uninstalling and re-installing I get the same messages with the same outcome of it closing down. Im sorry if this is the result of my doing but I am unsure as to how to change the outcome of this.

**Comment by ElliotGarbus** [comment]
Lets do this one step at a time.  Delete the ottobit app on your mac.  Just go to the app directory and move to trash.  Reinstall from the release page.   Pay close attention, you will need to go into settings/security & privacy to give the app permission to run.

**Comment by lfennew** [comment]
I deleted the application, then re-downloaded, and double clicked the file it then went through the security of which I followed the process and then it closed down again, this was the log from that process,Im really sorry about this, should I delete the kivy and otto bit hidden files in the directory?

[INFO   ] Logger: Record log in /Users/lewisennew/.kivy/logs/kivy_21-03-02_5.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/7550BC94-3B08-4E75-9B39-1BCC51C9556E/d/OttobitJrEdit.app/Contents/MacOS/kivy/__init__.pyc"
[INFO   ] Python: v3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] Python: Interpreter at "/private/var/folders/h5/jrhqnvc53dl7yscn779m7fxh0000gn/T/AppTranslocation/7550BC94-3B08-4E75-9B39-1BCC51C9556E/d/OttobitJrEdit.app/Contents/MacOS/OttobitJrEdit"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Failed creating OpenGL pixel format'
  File "site-packages/kivy/core/__init__.py", line 71, in core_select_lib
  File "site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
  File "site-packages/kivy/core/window/__init__.py", line 983, in __init__
  File "site-packages/kivy/core/window/window_sdl2.py", line 290, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 232, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[CRITICAL] App: Unable to get a Window, abort.

**Comment by ElliotGarbus** [comment]
Leave the .kivy directory, try deleting the main.ini file from the ottobit directory

**Comment by lfennew** [comment]
IT WORKEDDDDDDDD

**Comment by ElliotGarbus** [comment]
👍  Glad to hear it.
Go into each of the app specific directories and delete the main.ini files.
.pollymoon, .hedra...

**Comment by lfennew** [comment]
Brilliant, I have and they are now all open and working! thank you so much for helping with that, I just need to connect it with the midi I/o however I am using the midi in/out from my Arturia keyboard, would this work or should I just get a Roland UM-one?

**Comment by ElliotGarbus** [comment]
I don't know about the keyboard it is worth a try.  Start by having only one pedal and only one TRS cable connected to the MIDI I/O.  Make sure the MIDI ch of the Ottobit is different than the midi channel of the keyboard.  Set the Ottobit exp to MIDI, and midi thru to OUT.  Make sure you are using a trs cable.  Set the editor to use the same midi ch as the pedal.  Let me know if it connects.

**Comment by ElliotGarbus** [comment]
And connect the midi out of the MIDI I/O to the MIDI in of the keyboard, and the in of the MIDI I/O to the out of the keyboard.  If you have other midi software that works with the keyboard running, I would suggest closing those apps. 

Do you have any midi monitoring software?

**Comment by lfennew** [comment]
that's fair! I have one pedal and one trs into the otto bit, ive followed the above but it does not connect, however I have noticed that it knocks off the midi keys within Ableton when I connect the midi-in and out to the Meris IO, the keyboard is on a different channel , ive closed all the apps but it won't let me connect, 

Not that I am aware of no, I think I might need that Roland cable to be truthful

**Comment by lfennew** [comment]
btw the only midi monitoring software I have is the midi control centre from Arturia,

**Comment by ElliotGarbus** [comment]
It could be the keyboard is not passing sysex messages.  The editor requires midi sysex messages.   The Roland UM-One MKII will work.  
Here is a free midi monitor: https://www.snoize.com/midimonitor/
You can use it if you want to test what is going on...

**Comment by ElliotGarbus** [comment]
The first thing to test is that when you twist the knobs on the pedal, you are receiving messages.

**Comment by lfennew** [comment]
Brilliant, I have just purchased that cable so hopefully this will fix the issue and I can use your program! 

Thank you so much for your help on this, it really means a lot! if you have a patreon/paypal id be more than happy to buy you a pint as a thank you!

**Comment by ElliotGarbus** [comment]
Your welcome, I'm happy to help.   There is a donate item on the help menu that will take you to my paypal site.  I'll enjoy that pint after you have everything up and running.  
Don't hesitate to reach out if you have trouble, and let me know when you have it working.

**Comment by lfennew** [comment]
Hi Elliot, just want to let you know I got the cable and both the Ottobit and Hedra are working perfectly when they are separately connected, however when I try to connect both devices into the IO, the secondary connected device will not connect, they are both on separate Midi channels (Ottobit 16 / Hedra 4) but the interesting part is that both devices will match global bpm via Ableton, So the issue seems to be operating both pedals on both programs at the same time. any pointers? thank you,

**Comment by lfennew** [comment]
Hi Elliott, I believe ive solved it, one of the cables was not a TRS, both seem to be working in tandem now. :)

**Comment by ElliotGarbus** [comment]
Glad you got it all working!  Enjoy!
